services:
  # Backend API Service
  - type: web
    name: menuiq-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    
  # Frontend Web Service  
  - type: web
    name: menuiq-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://menuiq-backend.onrender.com$1
      - type: rewrite
        source: /*
        destination: /index.html

# Optional: Database (if you want to use PostgreSQL instead of SQLite)
# databases:
#   - name: menuiq-db
#     databaseName: menuiq
#     user: menuiq
